### ISSUE TITLE
Multiple java versions

### ISSUE THREAD

**Issue by RobertWielewicki** [sammko/picomc#14]
Im using OpenJDK 16.0.1 and Minecraft version 1.12.2 doesn't work with it. I know i should switch to Java 1.8 for linux, but I need OpenJDK for other things. Is there a way to choose Java version to execute? If no, it would be great to add. Either from path env. variable or from direct path.

**Comment by sammko** [comment]
You can set the `java.path` config option globally, or per instance. For example:
Global:
```picomc config set java.path /usr/lib/jvm/java-8-openjdk/bin/java```
per-instance:
```picomc instance config <instance-name> set java.path /usr/lib/jvm/java-8-openjdk/bin/java```

In addition, the `JAVA_HOME` env variable is respected, but it is overriden by both the global and instance specific configurations. Sorry for the lack of documentation.

**Comment by RobertWielewicki** [comment]
Thank you, it did work. 
PS1: If somebody needs a java from oracle from their site you need to register and go here https://www.oracle.com/java/technologies/javase/javase8-archive-downloads.html
PS2: Do you keep some contact to maybe help with documentation? I may help.

**Comment by RobertWielewicki** [comment]
Small bug found (I guess).
Since I don't need Java1.8 for much i decided to sudo ln -s java /bin/java1.8
And it finds it in tabfill in terminal, but if I set it in picomc it defaults to Java 16.
When i point directly to java (1.8) it works.
I have manually downloaded java, but I guess I will use java 8 from pacman

**Comment by sammko** [comment]
I'm not sure I understand what you mean. `picomc` uses the `subprocess` module to launch `java`. This looks up the `java` executable in the current `PATH` (analogous to the behaviour of `execvp(3)`.

**Comment by RobertWielewicki** [comment]
Well I was talking about picomc not following symlink to java, but I am pointing to absolute java file when i want Oracle for testing (OpenJDK seems better anyway)
