### ISSUE TITLE
picomc can't parse java version

### ISSUE THREAD

**Issue by K3y-1** [sammko/picomc#21]
I'm trying to launch latest release of minecraft which is 1.18<br/>
so I need java 17 installed, here is packages I installed on my ubuntu machine:<br/>
```openjdk-17-jdk-headless/focal-updates,now 17+35-1~20.04 amd64 [installed,automatic]
openjdk-17-jdk/focal-updates,now 17+35-1~20.04 amd64 [installed]
openjdk-17-jre-headless/focal-updates,now 17+35-1~20.04 amd64 [installed,automatic]
openjdk-17-jre/focal-updates,now 17+35-1~20.04 amd64 [installed] 
```
and this is what I get from `java --version`:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-120.04, mixed mode, sharing)
```
This is kinda strange, because before java 17 the version was like `openjdk version "1.16.0"`.<br/>
now when I try to lanch minecraft, it fails to parse java version.
this the error:
```
File "/home/hello/.local/lib/python3.8/site-packages/picomc/java/javainfo.py", line 53, in check_version_against
    major, minor, *_ = version.split(".")
ValueError: not enough values to unpack (expected at least 2, got 1)
```
I also tried to print the value of `version` in javainfo.py and it was `17`.

**Comment by sammko** [comment]
Yeah, this was an issue, should be fixed in 0.4.4, so I suppose you haven't updated. Try that please.

**Comment by K3y-1** [comment]
I tried to update picomc before encountering the version problem and I thought it was on version 0.4.4.
looks like my python environments are messed up a little bit as python packages on root user is different.
anyway thank you for the response🙏.

**Comment by sammko** [comment]
No problem, glad it works :)
