### ISSUE TITLE
Custom Arguments on launch?

### ISSUE THREAD

**Issue by TheSleepingAssassin** [sammko/picomc#28]
OS: Arch Linux

is there any way to provide custom launch arguments, I'm on linux so I have a problem where when you press 2 keyboard keys together then the input is delayed, e.g: if I press W and D at the same time, my character moves like 2 seconds later. This was a problem I had already encountered before and have a fix for it but that would require specifying a custom lwjgl library path in the java arguments. Is there a way to do this is picomc?  Also is there a formal list of configuration options or KEYS of instances that I could use?

**Comment by TheSleepingAssassin** [comment]
I've found that I can specify custom jvm args but when I input -Dorg.lwjgl.librarypath=/home/name/LWJGLFIX/ (LWJGLFIX is a directory with the fixed lwjgl binary) it says 
`Error: No such option: -D`
even when I put it in quotes

**Comment by sammko** [comment]
Hey! Sorry about the lack of documentation.

There's a `java.jvmargs` config option, which I take you have found. The default value is set here https://github.com/sammko/picomc/blob/597e670bbb2cc670905f6de48f61abded442dcba/picomc/config.py#L26
so you should probably include those flags as well, if you override it. The way to set an option value starting with a `-` is to use a `--` to signal the end of options, in standard GNU manner. Alternatively, you can find the config json file and modify it manually. For example to set the config option for the `default` instance to the defaults explicitly, you could run

`picomc instance config default set java.jvmargs -- "-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCP
auseMillis=50 -XX:G1HeapRegionSize=32M"`

What might be a better long-term, albeit more involved, solution would be to grab the version spec json file (found in `$PICOMC_ROOT/versions/$VERSION/$VERSION.json`) and modify it accordingly.

**Comment by TheSleepingAssassin** [comment]
It worked! Thanks for the help! There's one more thing I want to know is that are there only 4 config options available right now? I found them through `picomc config show`

**Comment by sammko** [comment]
Yeah, those are the only options currently used by picomc. There's also `version` on instances, but that's not really an option.
