### ISSUE TITLE
How to switch game directory?

### ISSUE THREAD

**Issue by Fabian42** [sammko/picomc#34]
I have an existing Minecraft directory. The default of picomc seems to be `~/.local/share/picomc/instances/default/minecraft`. I could symlink that, but that's not a very user-friendly method and it's not instance-dependent. I've tried inserting a "`dir`" config into the instance, that did nothing. Is this not implemented?

**Comment by Fabian42** [comment]
Actually, "default" seems to be an auto-created profile (which `play` always uses and creates if it doesn't exist, even if I did create a different profile manually, a bit weird), so it is actually profile-dependant. But still not very user-friendly.

**Comment by Fabian42** [comment]
It's also not "`gameDir`" like in `launcher_profiles.json`.
I have no idea which config options work anyway. I just tried…
`picomc instance config default set resolution "{"height":1035,"width":1920}"`
…from `launcher_profiles.json` and it also doesn't work.

**Comment by sammko** [comment]
Sorry this is unsupported and an uncommon use-case. I think a symlink should serve your needs well.

`picomc` operates in terms of "versions" and "instances". A version is a specific configuration of the game (e.g. vanilla 1.19, or 1.19.4 with fabric loader). An instance has a version attribute, which specifies how the game is launched and a game directory, which contains all the saves and mods etc. The standard way to use picomc is to first create an instance (`picomc instance create ...`) and launch it using `picomc instance launch ...`. To simplify this, the concept of the default instance is introduced, along with the play command. The play command automatically creates an instance called `default` using meta-version `latest` (which is always resolved to the most up to date release of the game) if it doesn't exist and launches it. It's just a shortcut for the underlying concepts.

Config options are undocumented, unfortunately and there's not that many of them ATM.

**Comment by Fabian42** [comment]
It's uncommon to have an existing Minecraft folder? Everyone who played with another launcher before has one. I would bet that this applies to 100% of your users.

**Comment by sammko** [comment]
I agree that having an existing Minecraft folder is a common situation to be in. What I considered uncommon is wanting to use a 3rd party launcher with its own concept of "instances" to launch in a game folder managed by a different launcher.

Sure, there exist launchers that use your existing .minecraft folder by default, but as far as I'm aware, they don't usually have the concept of "instances".

Consider MultiMC/PolyMC. Those have a similar instance system to picomc and manage their own game folders as well.

Anyway, I probably won't be adding functionality to support this. A symlink should work fine.

**Comment by Fabian42** [comment]
OK, thanks for explaining! I'll suggest a readme edit.

**Comment by Fabian42** [comment]
#35
