### ISSUE TITLE
Can't authentificate mojang account

### ISSUE THREAD

**Issue by TheK0tYaRa** [sammko/picomc#5]
When i execute
`picomc account authenticate my_account@gmail.com`
it returns
`AttributeError: 'OfflineAccount' object has no attribute 'authenticate'`
after i input a password.
That's not a big issue but still needs a fix.

picomc, version 0.4.2
Python 3.8.6

**Comment by sammko** [comment]
This is a result of poor documentation, it's definitely on my list to improve that. You need to specify the email on account creation, not authentication. For example

    picomc account create any_name my_account@gmail.com

and the later just

    picomc account authenticate any_name

The `any_name` acts just as an internal identifier, it need not match the email nor game username, that is retrieved from the API.
Please close this issue if solved. Thank you

**Comment by sammko** [comment]
I assume it works? Please comment if mis-closed.
